In [1]:
# importing library

import numpy as np

In [2]:
arr = np.array([[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10,11,12,13,14]])

In [3]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
np.size(arr)

15

In [6]:
np.shape(arr)

(3, 5)

In [7]:
arr = np.array([1,2 ,3, 4])

In [8]:
a = np.arange(15).reshape(3,5)

In [9]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
a.ndim

2

In [11]:
a.reshape(5, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
x = np.array([1, 2])
print(np.ndim(x))

1
